name = "beyondi-trading-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"

[[d1_databases]]
binding = "DB"
database_name = "beyondi_trading_db"
database_id = "60f22f30-ecbe-4a11-9556-c073e2c8e840"

